{% set name = "pyseobnr" %}
{% set version = "0.3.6" %}

# choose the oldest scipy possible, to maximise compatibility with user environments
{% set scipy_version = "1.13" %}
{% set scipy_version_v313 = "1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyseobnr-{{ version }}.tar.gz
  sha256: 46508432709e637e6661252b55675bfb002a4425b770bb94b0bb4194ccdc5b97
  patches:
    - nolalsuite-in-pyproject.patch

build:
  skip: true  # [win]
  script: |
    {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy {{ scipy_version }}              # [build_platform != target_platform and py<313]
    - scipy {{ scipy_version_v313 }}         # [build_platform != target_platform and py>=313]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - cython
    - numpy
    - pip
    - python
    - scipy {{ scipy_version }}              # [py<313]
    - scipy {{ scipy_version_v313 }}         # [py>=313]
    - setuptools
    - setuptools-scm >=3.4.3
    - wheel

  run:
    - h5py
    - numba
    - numexpr
    - numpy >=1.23.0
    - pygsl_lite
    - python
    - python-lal
    - python-lalsimulation
    - qnm
    - {{ pin_compatible('scipy') }}
    - scri
    - setuptools

test:
  requires:
    - pip
    - pytest
    - pandas
    - pycbc
  source_files:
    - test/
  commands:
    # This is disabled because scri and sxs have issues on pypi
    #- python -m pip check
    - python -m pip show pyseobnr
    - python -m pytest test/ -ra

about:
  summary: Gravitational wave modelling within the effective-one-body framework
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://git.ligo.org/waveforms/software/pyseobnr
  dev_url: https://git.ligo.org/waveforms/software/pyseobnr
  doc_url: https://waveforms.docs.ligo.org/software/pyseobnr/

extra:
  recipe-maintainers:
    - raffienficiaud
    - duncanmmacleod
    - lorenzopompili00
